// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjwXCpYHX6i5yBOQdWNjK0p8f8O7OR6-Q',
    appId: '1:357792314356:web:ef2b486cc75309393abfa1',
    messagingSenderId: '357792314356',
    projectId: 'simple-firebase-bloc-app',
    authDomain: 'simple-firebase-bloc-app.firebaseapp.com',
    storageBucket: 'simple-firebase-bloc-app.firebasestorage.app',
    measurementId: 'G-NLWCXCE8EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdJ6OAbm4mhpDl8Xkw5qkweK0Vpz2a7HU',
    appId: '1:357792314356:android:95614dd321b476893abfa1',
    messagingSenderId: '357792314356',
    projectId: 'simple-firebase-bloc-app',
    storageBucket: 'simple-firebase-bloc-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKX6dADt5f0TZMvxCuW1ItC-FpI4-r9nE',
    appId: '1:357792314356:ios:7e6978c76e9b78163abfa1',
    messagingSenderId: '357792314356',
    projectId: 'simple-firebase-bloc-app',
    storageBucket: 'simple-firebase-bloc-app.firebasestorage.app',
    iosBundleId: 'com.example.simpleFirebaseBlocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKX6dADt5f0TZMvxCuW1ItC-FpI4-r9nE',
    appId: '1:357792314356:ios:7e6978c76e9b78163abfa1',
    messagingSenderId: '357792314356',
    projectId: 'simple-firebase-bloc-app',
    storageBucket: 'simple-firebase-bloc-app.firebasestorage.app',
    iosBundleId: 'com.example.simpleFirebaseBlocApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjwXCpYHX6i5yBOQdWNjK0p8f8O7OR6-Q',
    appId: '1:357792314356:web:dd76f144267a38b83abfa1',
    messagingSenderId: '357792314356',
    projectId: 'simple-firebase-bloc-app',
    authDomain: 'simple-firebase-bloc-app.firebaseapp.com',
    storageBucket: 'simple-firebase-bloc-app.firebasestorage.app',
    measurementId: 'G-NQCZVWC4LH',
  );
}
